name: tcells-scvi
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - scanpy
  - anndata
  - pytorch
  - scvi-tools
  - pytorch
  - pytorch-lightning==2.2.*
  - torchmetrics==1.3.*
  - pyyaml
  - tqdm
  - pip:
      - gseapy
      - gprofiler-official

